webtalk_init -webtalk_dir D:/College/Masters/Winter_2019-20/ECEC661/HW4/bubbke_sort/bubbke_sort.sim/sim_1/behav/xsim/xsim.dir/bubble_logic_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 14 21:33:01 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2644227" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211827698_0_0_900" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9f4f6854-5e0e-4ad4-992f-e099c094e7bd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b21cf2120d214cdfa22f30abab09cdb5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "38" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2300 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.16_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6016_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3049634976 -regid "211827698_0_0_900" -xml D:/College/Masters/Winter_2019-20/ECEC661/HW4/bubbke_sort/bubbke_sort.sim/sim_1/behav/xsim/xsim.dir/bubble_logic_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/College/Masters/Winter_2019-20/ECEC661/HW4/bubbke_sort/bubbke_sort.sim/sim_1/behav/xsim/xsim.dir/bubble_logic_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/College/Masters/Winter_2019-20/ECEC661/HW4/bubbke_sort/bubbke_sort.sim/sim_1/behav/xsim/xsim.dir/bubble_logic_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
