# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/College/Masters/Winter_2019-20/ECEC661/HW4/bubble_sort_tb/bubble_sort_tb.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xci
# IP: The module: 'system_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/College/Masters/Winter_2019-20/ECEC661/HW4/bubble_sort_tb/bubble_sort_tb.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/College/Masters/Winter_2019-20/ECEC661/HW4/bubble_sort_tb/bubble_sort_tb.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/College/Masters/Winter_2019-20/ECEC661/HW4/bubble_sort_tb/bubble_sort_tb.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/College/Masters/Winter_2019-20/ECEC661/HW4/bubble_sort_tb/bubble_sort_tb.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xci
# IP: The module: 'system_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/College/Masters/Winter_2019-20/ECEC661/HW4/bubble_sort_tb/bubble_sort_tb.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/College/Masters/Winter_2019-20/ECEC661/HW4/bubble_sort_tb/bubble_sort_tb.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/College/Masters/Winter_2019-20/ECEC661/HW4/bubble_sort_tb/bubble_sort_tb.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
